databases:
  - name: steins-gate-anime
    plan: free
    databaseName: steins-gate-anime
    user: mysite

services:
  - type: web
    plan: free
    name: steins-gate-anime
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --chdir core"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
