# Generated by Django 6.0.2 on 2026-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('appearing', models.TextField()),
                ('type', models.TextField()),
                ('genres', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
