# Generated by Django 6.0.2 on 2026-02-20 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='animedescription',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='animedescription',
            name='appearing',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animedescription',
            name='genres',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='animedescription',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='animedescription',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainpage.animedescription'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
